CATEGORY_MASTER = [
    {"name":"Diagnostics & Monitoring","icon":"🩺"},
    {"name":"Surgical Instruments","icon":"🔪"},
    {"name":"Hospital & ICU Equipment","icon":"🏥"},
    {"name":"Laboratory","icon":"🧪"},
    {"name":"Medicines & Pharmacy","icon":"💊"},
    {"name":"Orthopedic & Braces","icon":"🦴"},
    {"name":"Cardiology","icon":"❤️"},
    {"name":"Respiratory Care","icon":"🫁"},
    {"name":"Diabetes Care","icon":"💉"},
    {"name":"Dental Care","icon":"🦷"},
    {"name":"Eye & ENT Care","icon":"👁️"},
    {"name":"Mother & Baby","icon":"👶"},
    {"name":"Physiotherapy & Rehab","icon":"🏃"},
    {"name":"Mobility Aids","icon":"♿"},
    {"name":"PPE & Safety","icon":"⛑️"},
    {"name":"Wound Care & First Aid","icon":"🩹"},
    {"name":"Disposables & Consumables","icon":"📦"},
    {"name":"IV & Infusion","icon":"💧"},
    {"name":"Sterilization & Hygiene","icon":"🧼"},
    {"name":"Neurology & Urology","icon":"🧠"},
    {"name":"Gynecology & Obstetrics","icon":"🤰"},
    {"name":"Pediatrics","icon":"🍼"},
    {"name":"Dermatology","icon":"🧴"},
    {"name":"Home Healthcare","icon":"🏠"},
    {"name":"Emergency & Ambulance","icon":"🚑"}
]